from __future__ import annotations

from enum import StrEnum


class EntityType(StrEnum):
    PERSON = "PERSON"
    ORGANIZATION = "ORGANIZATION"
    LOCATION = "LOCATION"
    DOCUMENT = "DOCUMENT"
    OTHER = "OTHER"


class EventType(StrEnum):
    COMMUNICATION = "COMMUNICATION"
    MEETING = "MEETING"
    DECISION = "DECISION"
    TRANSACTION = "TRANSACTION"
    ACTION = "ACTION"
    OTHER = "OTHER"


class ClaimKind(StrEnum):
    EVENT = "EVENT"
    RELATIONSHIP = "RELATIONSHIP"


class Polarity(StrEnum):
    AFFIRMED = "AFFIRMED"
    NEGATED = "NEGATED"
    UNKNOWN = "UNKNOWN"


class Modality(StrEnum):
    ASSERTED = "ASSERTED"
    POSSIBLE = "POSSIBLE"
    ALLEGED = "ALLEGED"
    CONDITIONAL = "CONDITIONAL"
    UNKNOWN = "UNKNOWN"


class TemporalPrecision(StrEnum):
    INSTANT = "INSTANT"
    DAY = "DAY"
    MONTH = "MONTH"
    YEAR = "YEAR"
    RANGE = "RANGE"
    UNRESOLVED = "UNRESOLVED"


class BuildStage(StrEnum):
    PARSE = "PARSE"
    EXTRACT = "EXTRACT"
    RESOLVE = "RESOLVE"
    GRAPH = "GRAPH"


class DocumentFailureCode(StrEnum):
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    ENCRYPTED = "ENCRYPTED"
    OCR_REQUIRED = "OCR_REQUIRED"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"
    MALFORMED = "MALFORMED"
    LOADER_FAILED = "LOADER_FAILED"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    ADAPTER_CONTRACT = "ADAPTER_CONTRACT"


class ReviewAction(StrEnum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    MERGE_ENTITIES = "MERGE_ENTITIES"
    UNMERGE_ENTITY = "UNMERGE_ENTITY"
    GROUP_EVENTS = "GROUP_EVENTS"
    UNGROUP_EVENT = "UNGROUP_EVENT"
    SET_CANONICAL_NAME = "SET_CANONICAL_NAME"
